=== CopperGiraffe/vertigo-libs/vertigo-account-api/src/main/java/io/vertigo/account/authorization/vertigo-security_1_1.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="authorisationConfig">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="globalAuthorization" type="authorization" />
				<xs:element name="secured-entity" type="secured-entity" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="authorization">
		<xs:attribute name="id" type="xs:string" use="required"/>
		
		<xs:attribute name="label" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="secured-entity">
		<xs:choice minOccurs="0" maxOccurs="1">
			<xs:element name="advanced-axes">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="advanced-axe" type="advanced-axe" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="operations">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="operation" type="operation" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		
		<xs:attribute name="entity" type="xs:string" use="required"/>
		<xs:attribute name="security-fields" type="xs:string" use="optional"/>		
	</xs:complexType>
	
	<xs:complexType name="advanced-axe">
		<xs:attribute name="field" type="xs:string" use="required"/>		
		<xs:attribute name="type" type="xs:string" use="required"/>	
		<xs:attribute name="values" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="operation">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="filter" type="filter" />
		</xs:sequence>			
		<xs:attribute name="name" type="xs:string" use="required"/>		
		<xs:attribute name="label" type="xs:string" use="required"/>
		<xs:attribute name="grants" type="xs:string" use="optional"/>
		<xs:attribute name="overrides" type="xs:string" use="optional"/>
		<xs:attribute name="filter" type="xs:string" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="filter">
		<xs:attribute name="rule" type="xs:string" use="required"/>	
	</xs:complexType>
</xs:schema>

=== CopperGiraffe/vertigo-libs/vertigo-persona-impl/src/test/java/io/vertigo/persona/security/advanced-auth-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<authorisationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="vertigo-security_1_1.xsd">
	
	<!-- Globals Permissions -->
	<permission id="PRM_ADMUSR" label="Administration utilisateurs"/>		
	<permission id="PRM_ADMPRO" label="Administration profiles"/>	
	<permission id="PRM_ADMAPP" label="Administration application"/>	
	
	<secured-entity entity="MARCHE" security-fields="OWNER_UTI_ID, TYP_ID, ENVELOPPE_GLOBALE">
		<advanced-axes>
			<advanced-axe field="ETA_CD" type="ENUM" values="CRE, VAL, PUB, NOT, REA, ARC"/>
		</advanced-axes>
		<operations>
			<!-- Visibilité attribuable avec un montant maximum, et visibilité pour l'utilisateur créateur. -->
			<operation name="READ" label="Lecture">
				<filter rule="ENVELOPPE_GLOBALE&lt;=${montantMax}"/> <!-- multiple filter are OR -->
				<filter rule="OWNER_UTI_ID=${utiId}"/>
			</operation>
			
			<!-- Visibilité globale attribuée avec une opération transverser Hors Périmètre. Sans règles = toujours ok. -->
			<operation name="READ_HP" label="Lecture hors périmètre" overrides="READ" filter="always"/>
			
			<!-- Ecriture possible par l'utilisateur créateur avant que le marché ne soit Archivé, ou avec un montant max avant Archivé. -->
			<operation name="WRITE" grants="READ" label="Edition">
				<filter rule="OWNER_UTI_ID=${utiId} and ETA_CD&lt;'ARC'"/> <!-- OR -->
				<filter rule="TYP_ID=${typId} and ENVELOPPE_GLOBALE&lt;=${montantMax} and ETA_CD&lt;'ARC'"/>
			</operation>
			
			<!-- Création attribuable par type et par montant maximum. -->
			<operation name="CREATE" grants="READ" label="Creation" filter="TYP_ID=${typId} and ENVELOPPE_GLOBALE&lt;=${montantMax}"/>
			
			<!-- "Suppression attribuable par type de marché ou pour le créateur tant que non Publié (Attribué sans type = règle non vérifiée). -->
			<operation name="DELETE" grants="READ, WRITE"  label="Suppression">
				<filter rule="TYP_ID=${typId}"/> <!-- OR -->
				<filter rule="OWNER_UTI_ID,=${utiId} and ETA_CD&lt;'PUB'"/>
			</operation>
		</operations>		
	</secured-entity>	
</authorisationConfig>
